# Generated by Django 3.0.4 on 2020-11-16 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la categoria')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion del Producto')),
                ('fechaRegistro', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Nombre de la categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Producto')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('categoria', models.IntegerField(default=0, verbose_name='Categoria del Producto')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagen/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
    ]
