# Generated by Django 3.0.4 on 2020-11-16 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20201115_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='type',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Categoria', verbose_name='Categoria'),
        ),
    ]
