# Generated by Django 3.0.4 on 2020-11-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20201115_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='Descripcion de la categoria'),
        ),
    ]
